### ISSUE TITLE
Can you add a license?

### ISSUE THREAD

**Issue by allglc** [IdoGalil/benchmarking-uncertainty-estimation-performance#1]
Hello,
Thanks for the work. However, without license information, "no one may reproduce, distribute, or create derivative works from your work." [(source)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license), so could you specify a e.g. MIT license?
Thanks in advance.

**Comment by IdoGalil** [comment]
Hey, the MIT license was added. I hope this work helps you.

**Comment by allglc** [comment]
Thanks! Yes it does.
